version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: dotnet build -c Release src
test_script:
- cmd: dotnet test -c Release src/Hedgehog.Experimental.Tests
artifacts:
- path: '**\Release\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: cHiHWRM0/bGYrKcEGO76wBN8OQ8WTgg4fpqCoLsbCyIznl0wKOqEcBdKC8YyikKB
  on:
    appveyor_repo_tag: true
