name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8
    - name: Build
      run: dotnet build -c Release src
    - name: Test F#
      run: dotnet test -c Release src/Hedgehog.Experimental.Tests
    - name: Test C#
      run: dotnet test -c Release src/Hedgehog.Experimental.CSharp.Tests
    - name: Publish NuGet
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        PROJECT_FILE_PATH: "src/Hedgehog.Experimental/Hedgehog.Experimental.fsproj"
        PACKAGE_NAME: "Hedgehog.Experimental"
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
